<?php

$seedsFirstNames = [
    'Jonas', 'Petras', 'Kazys',
    'Rimas', 'Stepas', 'Laurynas', 'Benas', 'Rokas', 'Linas',
    'Antanas', 'Simas', 'Alanas', 'Ugnius', 'Onius', 'Barbaras',
    'Kristijonas', 'Kristoferis', 'Remigijus', 'Ernestas', 'Evaldas', 'Augustas', 'Adomas',
    'Arijus', 'Adas', 'Aleksej', 'Balys', 'Boris', 'Bertas', 'Bogdanas', 'Džiugas', 'Domas',
    'Denis', 'Dimitrijus', 'Edvinas', 'Erikas', 'Evanas', 'Eidvudas', 'Elvinas',
    'Faustas', 'Fedoras', 'Gustas', 'Giedrius', 'Germanas', 'Gotautas', 'Haris',
    'Hugas', 'Henris', 'Hektoras', 'Karolis', 'Kristupas', 'Kostas', 'Kęstutis',
    'Boedyn', 'Bogdan', 'Bohbi', 'Bony', 'Bowen', 'Bowie', 'Boyd', 'Bracken', 'Brad',
    'Bradan', 'Braden', 'Bradley', 'Bradlie', 'Bradly', 'Brady', 'Bradyn', 'Braeden',
    'Braiden', 'Brajan', 'Brandan', 'Branden', 'Brandon', 'Brandonlee', 'Brandon-Lee', 'Brandyn',
    'Brannan', 'Brayden', 'Braydon', 'Braydyn', 'Breandan', 'Brehme', 'Brendan', 'Brendon', 'Brendyn',
    'Breogan', 'Bret', 'Brett', 'Briaddon','Brian', 'Brodi',
    'Brodie', 'Brody', 'Brogan', 'Broghan', 'Brooke', 'Brooklin',
     'Brooklyn', 'Bruce', 'Bruin', 'Bruno', 'Brunon',
     'Davie', 'Davis', 'Davy', 'Dawid', 'Dawson', 'Dawud', 'Dayem', 'Daymian', 'Deacon',
     'Deagan', 'Dean', 'Deano', 'Decklan', 'Declain',
     'Georgia', 'Georgy', 'Gerard', 'Ghyll', 'Giacomo', 'Gian', 'Giancarlo', 'Gianluca', 'Gianmarco',
     'Gideon', 'Gil', 'Gio', 'Girijan', 'Girius', 'Gjan', 'Glascott', 'Glen',
     'Glenn', 'Gordon', 'Grady', 'Graeme', 'Graham',
     'Grahame', 'Grant', 'Grayson', 'Greg', 'Gregor', 'Gregory', 'Greig', 'Griffin', 'Griffyn'
];
$seedsLastNames = [
    'Aloninas', 'Krepauskas', 'Zigmavičius', 'Petravičius', 'Arzinskas', 'Perkinskas',
    'Rolonavičius', 'Aržauskas', 'Baginskas', 'Lapinskas', 'Aminskas', 'Pojus', 'Narbutas',
    'Parisius', 'Birštonas', 'Grigorijus', 'Landinskis', 'Grikis', 'Petranauskonas','X1',
    'A2','BC3','AZ4','XOD','AA3','DD5','RNZ','B14','Z13','A2243','Pavardenis', 'Rndo', 'Z23',   'Carrillo',
    'Carroll','Carson','Carter','Carver','Case','Casey','Cash','Castaneda','Castillo','Castro','Cervantes','Chambers',
    'Chan',
    'Chandler',
    'Chaney',
    'Chang',
    'Chapman',
    'Charles',
    'Chase',
    'Chavez',
    'Chen',
    'Cherry',
    'Christensen',
    'Christian',
    'Church',
    'Clark',
    'Clarke',
    'Clay',
    'Clayton',
    'Clements',
    'Clemons',
    'Cleveland',
    'Cline',
    'Cobb',
    'Cochran',
    'Coffey',
    'Cohen',
    'Cole',
    'Coleman',
    'Collier',
    'Collins',
    'Colon',
    'Combs',
    'Compton',
    'Conley',
    'Conner',
    'Conrad',
    'Contreras',
    'Conway',
    'Cook',
    'Cooke',
    'Cooley',
    'Cooper',
    'Copeland',
    'Cortez',
    'Cote',
    'Cotton',
    'Cox',
    'Craft',
    'Craig',
    'Crane',
    'Crawford',
];
$seedsProjects = [
    'Project X', 'PHP Project', 'Bussiness Page', 'Greenscreen', 'Weather App',
    'Mario Game', 'Google Maps', 'Data analysis FF15', 'Random Project 15', 'Random Project 22',
    'Java Course', 'Windows xx10', 'Sound Check', 'Random Project 11', 'News Flash', 'Reddit',
    'Layout V12', 'Moew moew', 'Biology', 'Prinston', 'Another one', 'Project XO', 'Project 11',
    'Proejct 10', 'Woof woof', 'Random name', 'Hello world', 'Flashy'
];
